name: test api
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Resources/config/requirements.txt

      - name: Run Tests
        run: |
          robot -i regressivo -d report Resources/TestCases/POST-criarAdmin.robot
