name: test api
on: 
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4  # Atualizado para v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Resources/config/requirements.txt

      - name: Run Tests
        run: |
          robot -L TRACE -i smoke -d report Resources/TestCases

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: robot-report
          path: report/
